import { useCallback, useEffect, useState, type FormEvent } from 'react';
import AddIcon from '@mui/icons-material/Add';
import { Alert, Button, Grid2, MenuItem, Paper, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from '@mui/material';

import { advancedApi, type MonthlyPass, type ParkingLocationOption } from '@/features/advanced/advancedApi';
import { VEHICLE_TYPES, vehicleTypeLabels, type VehicleType } from '@/shared/constants/parking';
import { LoadingState } from '@/shared/components/LoadingState';
import { PageHeader } from '@/shared/components/PageHeader';
import { getApiErrorMessage } from '@/shared/utils/apiError';

const today = () => new Date().toISOString().slice(0, 10);
const nextMonth = () => { const value = new Date(); value.setMonth(value.getMonth() + 1); return value.toISOString().slice(0, 10); };

export function MonthlyPassPage() {
  const [passes, setPasses] = useState<MonthlyPass[]>([]);
  const [locations, setLocations] = useState<ParkingLocationOption[]>([]);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string>();
  const load = useCallback(async () => { setLoading(true); setError(undefined); try { const [passResponse, locationResponse] = await Promise.all([advancedApi.passes(), advancedApi.locations()]); setPasses(passResponse.data ?? []); setLocations(locationResponse.data ?? []); } catch (requestError) { setError(getApiErrorMessage(requestError, 'Unable to load monthly passes.')); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function createPass(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const values = new FormData(form); const validFrom = String(values.get('valid_from')); const validUntil = String(values.get('valid_until')); if (validUntil < validFrom) { setError('Pass end date must not be before its start date.'); return; } setSaving(true); setError(undefined); try { const response = await advancedApi.createPass({ vehicle_number: String(values.get('vehicle_number')), vehicle_type: String(values.get('vehicle_type')) as VehicleType, holder_name: String(values.get('holder_name')), mobile: String(values.get('mobile')) || null, parking_location_id: String(values.get('parking_location_id')) || null, valid_from: validFrom, valid_until: validUntil, amount: String(values.get('amount')), status: 'active' }); if (!response.data) throw new Error(response.message); form.reset(); await load(); } catch (requestError) { setError(getApiErrorMessage(requestError, 'Unable to create monthly pass.')); } finally { setSaving(false); } }
  return <><PageHeader title="Monthly passes" description="Create and track vehicle monthly parking memberships." />{error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}<Paper component="form" onSubmit={createPass} variant="outlined" sx={{ p: { xs: 2, md: 3 }, mb: 3 }}><Typography variant="h6" fontWeight={800} mb={2}>Create monthly pass</Typography><Grid2 container spacing={2}><Grid2 size={{ xs: 12, md: 4 }}><TextField name="vehicle_number" label="Vehicle number" required fullWidth /></Grid2><Grid2 size={{ xs: 12, md: 4 }}><TextField select name="vehicle_type" label="Vehicle type" defaultValue="car" fullWidth>{VEHICLE_TYPES.map((type) => <MenuItem key={type} value={type}>{vehicleTypeLabels[type]}</MenuItem>)}</TextField></Grid2><Grid2 size={{ xs: 12, md: 4 }}><TextField name="holder_name" label="Holder name" required fullWidth /></Grid2><Grid2 size={{ xs: 12, md: 4 }}><TextField name="mobile" label="Mobile" placeholder="9876543210" fullWidth /></Grid2><Grid2 size={{ xs: 12, md: 4 }}><TextField select name="parking_location_id" label="Parking location" defaultValue="" fullWidth><MenuItem value="">Any location</MenuItem>{locations.map((location) => <MenuItem key={location.id} value={location.id}>{location.name}</MenuItem>)}</TextField></Grid2><Grid2 size={{ xs: 12, md: 4 }}><TextField name="amount" label="Amount" type="number" inputProps={{ min: 0, step: '0.01' }} required fullWidth /></Grid2><Grid2 size={{ xs: 12, md: 6 }}><TextField name="valid_from" label="Valid from" type="date" defaultValue={today()} InputLabelProps={{ shrink: true }} required fullWidth /></Grid2><Grid2 size={{ xs: 12, md: 6 }}><TextField name="valid_until" label="Valid until" type="date" defaultValue={nextMonth()} InputLabelProps={{ shrink: true }} required fullWidth /></Grid2><Grid2 size={12}><Button type="submit" variant="contained" startIcon={<AddIcon />} disabled={saving}>{saving ? 'Saving…' : 'Create monthly pass'}</Button></Grid2></Grid2></Paper><Paper variant="outlined" sx={{ overflowX: 'auto' }}>{loading ? <LoadingState label="Loading monthly passes…" /> : <Table sx={{ minWidth: 760 }}><TableHead><TableRow><TableCell>Pass no.</TableCell><TableCell>Vehicle</TableCell><TableCell>Holder</TableCell><TableCell>Valid until</TableCell><TableCell>Amount</TableCell><TableCell>Status</TableCell></TableRow></TableHead><TableBody>{passes.map((pass) => <TableRow key={pass.id}><TableCell>{pass.pass_number}</TableCell><TableCell>{pass.vehicle_number}</TableCell><TableCell>{pass.holder_name}</TableCell><TableCell>{new Date(pass.valid_until).toLocaleDateString()}</TableCell><TableCell>₹{pass.amount}</TableCell><TableCell sx={{ textTransform: 'capitalize' }}>{pass.status}</TableCell></TableRow>)}</TableBody></Table>}</Paper></>;
}
